#!/bin/sh

set -e

piddir=/var/lib/yandex-ppb-memcached/pid

if [ "$1" = 'configure' ]; then
    if [ -z "$2" ]; then
        chmod 777 $piddir
        chmod +t $piddir
    elif dpkg --compare-versions "$2" lt "2.0.0"; then
        rm -f /etc/init.d/yandex-ppb-memcached
    fi
fi
